# Generated by Django 4.1.7 on 2023-03-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact_alter_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
