version: '3'

services:
  app:
    image: termproject:latest
    build:
      dockerfile: deploy/Dockerfile
      context: ..
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
    restart: always

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Termproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17456
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
