# Generated by Django 4.1.5 on 2023-01-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratingstar",
            options={
                "ordering": ["-value"],
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
            },
        ),
    ]
