# Generated by Django 4.1.7 on 2023-03-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_alter_pin_category_alter_pin_img_alter_pin_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='text',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pincategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pins.pincategory', verbose_name='Pin Category'),
        ),
    ]
