name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./deploy
          dockerfile: ./Dockerfile
          push: true
          tags: joseph7cartaphilus/termproject:latest
