name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build ./deploy -t josephfan/termproject:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: josephfan
          password: Joseph789

      - name: Push Docker image
        run: docker push termproject:latest
